//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugBooking
    {
        public int Id { get; set; }
        public int sender_id { get; set; }
        public int receiver_id { get; set; }
        public System.DateTime datetime { get; set; }
        public string delivery_status { get; set; }
        public string transaction_status { get; set; }
        public int quantity { get; set; }
        public int logistic_id { get; set; }
        public int DrugList_owner_id { get; set; }
        public int DrugList_drug_Id { get; set; }
    
        public virtual Logistic Logistic { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Pharmacist Pharmacist { get; set; }
        public virtual DrugList DrugList { get; set; }
    }
}
