//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRating
    {
        public int Id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public System.DateTime commentDate { get; set; }
        public int EquipmentId { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
