//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentBooking
    {
        public int Id { get; set; }
        public System.DateTime datetime { get; set; }
        public bool status { get; set; }
        public int quantity { get; set; }
        public int DoctorId { get; set; }
        public int LogisticId { get; set; }
        public int EquipmentId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Logistic Logistic { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
